version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: homeassistant/raspberrypi4-homeassistant:stable
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    network_mode: host
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homeassistant.rule=Host(`assistant.internal.${HOSTNAME}`)"
      - "traefik.http.routers.homeassistant.entrypoints=web-secure"
      - "traefik.http.routers.homeassistant.tls=true"
      - "traefik.http.routers.homeassistant.tls.certResolver=primary"
      - "traefik.http.services.homeassistant.loadbalancer.server.port=8123"
