version: "3.3"

services:
  traefik:
    image: traefik:v2.3
    container_name: traefik
    command:
      # - "--log.level=DEBUG"
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entryPoints.web-secure.address=:443
      - --serverstransport.insecureskipverify=true
      - --certificatesResolvers.primary.acme.email=${CLOUDFLARE_EMAIL}
      - --certificatesResolvers.primary.acme.storage=acme.json
      - --certificatesResolvers.primary.acme.dnsChallenge=true
      - --certificatesResolvers.primary.acme.dnsChallenge.provider=cloudflare
      - --certificatesResolvers.primary.acme.dnsChallenge.delayBeforeCheck=0
    environment:
      - CLOUDFLARE_EMAIL=${CLOUDFLARE_EMAIL}
      - CLOUDFLARE_API_KEY=${CLOUDFLARE_API_KEY}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./acme.json:/acme.json"
    networks:
      - web
    extra_hosts:
      - host.docker.internal:172.17.0.1
    labels:
      # wildcard certs
      - "traefik.http.routers.api.tls.domains[0].main=internal.${HOSTNAME}"
      - "traefik.http.routers.api.tls.domains[0].sans=*.internal.${HOSTNAME}"

networks:
  web:
    external: true
