version: "3.9"

services:
  unifi-controller:
    image: jacobalberty/unifi:6.1.71
    container_name: unifi-controller
    restart: unless-stopped
    init: true
    user: unifi
    environment:
      - TZ='America/Vancouver'
      - JVM_MAX_HEAP_SIZE=1024M
      - JVM_MAX_THREAD_STACK_SIZE=1280k
    volumes:
      - './data:/unifi/data' # unifi config data
      - './log:/unifi/log' # unifi log files
      - './run:/unifi/run' # system - place to put .pid files
      - './cert:/unifi/cert' # optional - for using custom SSL certs
      - './init.d:/unifi/init.d' # optional - startup scripts
    ports:
      - 8080:8080/tcp # Device command/control
      - 8443:8443/tcp # Web interface + API
      - 8843:8843/tcp # HTTPS portal
      - 8880:8880/tcp # HTTP portal
      - 3478:3478/udp # STUN service
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.unifi.rule=Host(`unifi.internal.${HOSTNAME}`)"
      - "traefik.http.routers.unifi.entrypoints=web-secure"
      - "traefik.http.routers.unifi.tls=true"
      - "traefik.http.routers.unifi.tls.certResolver=primary"
      - "traefik.http.services.unifi.loadbalancer.server.port=8443"
      - "traefik.http.services.unifi.loadbalancer.server.scheme=https"

networks:
  web:
    external: true
